/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ImageSitemapDotxmlRouteImport } from './routes/image-sitemap[.]xml'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCronCleanupWaitlistRouteImport } from './routes/api/public/cron/cleanup-waitlist'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageSitemapDotxmlRoute = ImageSitemapDotxmlRouteImport.update({
  id: '/image-sitemap.xml',
  path: '/image-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronCleanupWaitlistRoute =
  ApiPublicCronCleanupWaitlistRouteImport.update({
    id: '/api/public/cron/cleanup-waitlist',
    path: '/api/public/cron/cleanup-waitlist',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/changelog': typeof ChangelogRoute
  '/customers': typeof CustomersRoute
  '/image-sitemap.xml': typeof ImageSitemapDotxmlRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/cron/cleanup-waitlist': typeof ApiPublicCronCleanupWaitlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/changelog': typeof ChangelogRoute
  '/customers': typeof CustomersRoute
  '/image-sitemap.xml': typeof ImageSitemapDotxmlRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/cron/cleanup-waitlist': typeof ApiPublicCronCleanupWaitlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/changelog': typeof ChangelogRoute
  '/customers': typeof CustomersRoute
  '/image-sitemap.xml': typeof ImageSitemapDotxmlRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/cron/cleanup-waitlist': typeof ApiPublicCronCleanupWaitlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/changelog'
    | '/customers'
    | '/image-sitemap.xml'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/api/public/cron/cleanup-waitlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/changelog'
    | '/customers'
    | '/image-sitemap.xml'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/api/public/cron/cleanup-waitlist'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/changelog'
    | '/customers'
    | '/image-sitemap.xml'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/api/public/cron/cleanup-waitlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ChangelogRoute: typeof ChangelogRoute
  CustomersRoute: typeof CustomersRoute
  ImageSitemapDotxmlRoute: typeof ImageSitemapDotxmlRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicCronCleanupWaitlistRoute: typeof ApiPublicCronCleanupWaitlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-sitemap.xml': {
      id: '/image-sitemap.xml'
      path: '/image-sitemap.xml'
      fullPath: '/image-sitemap.xml'
      preLoaderRoute: typeof ImageSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/cleanup-waitlist': {
      id: '/api/public/cron/cleanup-waitlist'
      path: '/api/public/cron/cleanup-waitlist'
      fullPath: '/api/public/cron/cleanup-waitlist'
      preLoaderRoute: typeof ApiPublicCronCleanupWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ChangelogRoute: ChangelogRoute,
  CustomersRoute: CustomersRoute,
  ImageSitemapDotxmlRoute: ImageSitemapDotxmlRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicCronCleanupWaitlistRoute: ApiPublicCronCleanupWaitlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
